### ISSUE TITLE
When I trained for around 10 epochs, KL loss became NAN

### ISSUE THREAD

**Issue by lorafei** [SUTDBrainLab/MGP-VAE#2]

**Comment by lorafei** [comment]
![2061598515915_ pic_hd](https://user-images.githubusercontent.com/25504824/91511610-a67b4100-e912-11ea-8c65-15ca925854bf.jpg)
![2161598533441_ pic_hd](https://user-images.githubusercontent.com/25504824/91511640-b7c44d80-e912-11ea-939b-c4f6f176d71f.jpg)

**Comment by shagunuppal** [comment]
Hi, you can try increasing the fac parameter (e.g. close to 1 for MNIST) in the covariance_fns.py and that shall resolve the nan issue.
