### ISSUE TITLE
typo error in prediction_geodesic.py

### ISSUE THREAD

**Issue by aakash-saboo** [SUTDBrainLab/MGP-VAE#3]
Hi @shagunuppal @sarthak268 
THanks for the implementation.
In prediction_geodesic.py,
`def find_etta_i(z0, z1, z2):

	z0 = z0.view(NUM_SAMPLE_GEO_OUTPUT, -1).data
	z1 = Variable(z0, requires_grad = True)
	z2 = z2.view(NUM_SAMPLE_GEO_OUTPUT, -1)

	dec = decoder(torch.cat([Z_remaining, z1.view(1, NUM_SAMPLE_GEO_OUTPUT, -1)], 1))
	v = decoder(torch.cat([Z_remaining, z2.view(1, NUM_SAMPLE_GEO_OUTPUT, -1)], 1)) - \
	2*dec + decoder(torch.cat([Z_remaining, z0.view(1, NUM_SAMPLE_GEO_OUTPUT, -1)], 1))
	dec.backward(v, retain_graph=True)
	etta = -dt * z1.grad
	return etta`
In the above function, the second line should be `Variable(z1,requires_grad=True)` instead of `Variable(z0,requires_grad=True)` because we are trying to calculate energy wrt to z1.
PLease let me know if there is any correction.
Thanks

**Comment by sarthak268** [comment]
Thanks for letting us know.

**Comment by aakash-saboo** [comment]
Hi
Can you please also clarify why `.data` is used for `z0` and not for `z2`?

Thanks
