### ISSUE TITLE
typo error in prediction_geodesic.py - sum_energy function

### ISSUE THREAD

**Issue by aakash-saboo** [SUTDBrainLab/MGP-VAE#4]
Hi @sarthak268 @shagunuppal 
the code of the function is 
`def sum_energy(z_collection):
	
	delta_e = torch.FloatTensor(1, NUM_SAMPLE_GEO_OUTPUT, NDIM).zero_().cuda()
	for i in range(1, N-2):
		delta_e += find_energy(z_collection[i-1].view(NUM_SAMPLE_GEO_OUTPUT, -1) ,z_collection[i].view(NUM_SAMPLE_GEO_OUTPUT, -1) ,z_collection[i+1].view(NUM_SAMPLE_GEO_OUTPUT, -1))

	# energy_arr: a float tensor of size = (num_frames) where each index corresponds to energy of each point
	energy_arr = compute_norm(Variable(delta_e))
	energy_sum = (torch.sum(energy_arr)).item()

	return energy_sum`

According to the default arguments/values of the variable, z_collection consist of 6 vectors(initial vec,interpolated(4 vecs),final vec).
in the loop `for i in range(1,N-2)`, N=5, so i will have values {1,2}, which means that the triplets to be considered are with indexes {0,1,2} and {1,2,3}.
But in order to calculate sum of the whole geodesic path, 'i' should take values {1,2,3,4}. So the revised loop should be `for i in range(1,N)`

Let me know if there is this correction or not.
Thanks
Aakash

**Comment by shagunuppal** [comment]
Corrected. Thanks!
