### ISSUE TITLE
RuntimeError: shape '[64, 1, 64, 64]' is invalid for input of size 32768

### ISSUE THREAD

**Issue by divya1550** [SUTDBrainLab/MGP-VAE#7]
While I am executing "style_transfer_across_videos.py" file in Google Colab, I am facing Runtime error the details of which are shown below. Could anyone please suggest the solution to this error.

```
tcmalloc: large alloc 1073741824 bytes == 0x198abe000 @  0x7fd883f22b6b 0x7fd883f42379 0x7fd839726e4e 0x7fd839728dca 0x7fd83a36cd62 0x7fd83a48ab1b 0x7fd878a4f86f 0x7fd878e2fcff 0x7fd878e3548a 0x7fd878ccfaf2 0x551555 0x5a9dac 0x50a433 0x50beb4 0x507be4 0x508ec2 0x594a01 0x549e8f 0x5515c1 0x5a9dac 0x50a433 0x50cc96 0x507be4 0x508ec2 0x594a01 0x549e8f 0x5515c1 0x5a9dac 0x50a433 0x50beb4 0x507be4
Traceback (most recent call last):
  File "style_transfer_across_videos.py", line 38, in <module>
    X1, KL1, muL1, det_q1 = encoder(video1)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/MGP-VAE/networks.py", line 149, in forward
    x = x.view(BATCH_SIZE * NUM_FRAMES, NUM_INPUT_CHANNELS, H, W)
RuntimeError: shape '[64, 1, 64, 64]' is invalid for input of size 32768
```

**Comment by sarthak268** [comment]
What value of arguments have you used for BATCH_SIZE and NUM_FRAMES?

**Comment by divya1550** [comment]
Hello sir,

Thank you for the reply

Batch_size=8
Num_frames=8

same as original code

**Comment by sarthak268** [comment]
For running this script, you must turn the IS_TRAINING flag False.

**Comment by divya1550** [comment]
Traceback (most recent call last): File "style_transfer_across_videos.py",
line 8, in <module> from flags import * File "/content/MGP-VAE/flags.py",
line 41, in <module> parser.add_argument('--is_training', type=bool,
default=false, help="flag to indicate if it is training or inference.")
NameError: name 'false' is not defined

**Comment by divya1550** [comment]
please ignore previous reply.. I kept it as False

**Comment by divya1550** [comment]
tcmalloc: large alloc 1073741824 bytes == 0x19804a000 @ 0x7feb00353b6b
0x7feb00373379 0x7feab5b57e4e 0x7feab5b59dca 0x7feab679dd62 0x7feab68bbb1b
0x7feaf4e8086f 0x7feaf5260cff 0x7feaf526648a 0x7feaf5100af2 0x551555
0x5a9dac 0x50a433 0x50beb4 0x507be4 0x508ec2 0x594a01 0x549e8f 0x5515c1
0x5a9dac 0x50a433 0x50cc96 0x507be4 0x508ec2 0x594a01 0x549e8f 0x5515c1
0x5a9dac 0x50a433 0x50beb4 0x507be4 THCudaCheck FAIL
file=/pytorch/aten/src/THC/THCGeneral.cpp line=383 error=11 : invalid
argument

This is the error I am facing now

**Comment by divya1550** [comment]
Thank you for your timely response
